### ISSUE TITLE
issue with tree command output 

### ISSUE THREAD

**Issue by gl101** [rgs1/zk_shell#28]
1. The tree command shows the tree from right to left instead of left to right

2. Using non-interactive mode e.g.
export ZKSHELL_SRC=1; bin/zk-shell --run-once "tree /" localhost:2181 |  less
I get "'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)" (followed by 'usage' help for the tree command)
If in the non-interactive invocation above I dont pipe the output (ie. no |less), just let it go to stdout then the tree output does appear (no such ascii codec error).

**Comment by rgs1** [comment]
Thanks for reporting @gl101 ! For the first thing, I am not sure what you mean. The tree does get display from left to right:

```shell
~ ✔ zk-shell 0
Welcome to zk-shell (1.0.06)
(CONNECTING) /> 
(CONNECTED) /> tree
.
├── zookeeper
│   ├── config
│   ├── quota
│   │   ├── limits
│   │   │   ├── by-path
│   │   │   ├── slices
│   │   │   ├── global
│   │   ├── stats
│   │   │   ├── by-path
│   │   │   ├── global
(CONNECTED) /> 
```
Could you please provide an example of what you mean? For the 2nd issue, you are right, we should encode to utf-8 if we want this to work when outputting to a pipe (i.e.: using | less), as per:

http://stackoverflow.com/questions/492483/setting-the-correct-encoding-when-piping-stdout-in-python

I'll submit a fix for that shortly.  Thanks!

**Comment by gl101** [comment]
Hi Raul, Thanks for the quick reply.
And thanks for zkshell, I just started playing with it today and its been
very useful already.

On my machine (I use putty to connect to an Ubunto VM) when I use 'tree'
everything is right aligned.
Below is a paste from the putty. The three weird characters you see are
actually displayed to the right of "delete_topics" and seem to appear
instead of the '|' you show in your output.

-------
(CONNECTED) /> tree /admin
.
גגג delete_topics
(CONNECTED) />
-------

There is no special configuration to my putty and I havent seen something
like this occur before.

btw, I plan to submit a feature request (that DU or some alternative
command output a count of the number of znodes, not just sum of their
sizes).

Thanks again for your work.

Regards, Guy

**Comment by rgs1** [comment]
@gl101 : note that there is child_count for counting znodes under a path:

```shell
(CONNECTED) /> man child_count

NAME
        child_count - Prints the child count for paths

SYNOPSIS
        child_count [path] [depth]

OPTIONS
        * path: the path (default: cwd)
        * max_depth: max recursion limit (0 is no limit) (default: 1)

EXAMPLES
        > child-count /
        /zookeeper: 2
        /foo: 0
        /bar: 3


```

**Comment by gl101** [comment]
thats perfect! thanks.

**Comment by rgs1** [comment]
@gl101 : this https://github.com/rgs1/zk_shell/commit/8fe145d326456c4f87328b2788a0680db7d292bf should fix it, could you please try? Thanks!

**Comment by gl101** [comment]
Great, its working for me.
Thank you
Regards,
Guy

**Comment by rgs1** [comment]
@gl101 : what about right to left output?

**Comment by gl101** [comment]
Hi Raul, I think this part was still not working for me. I havent had time
to check again to be sure -  things are hectic at the moment. I will be in
touch when I check.
Thanks, Guy

**Comment by gl101** [comment]
Hi Raul, I just checked the latest zkshell version and the right to left
output in 'tree' still occurs for me.
Regards, Guy

**Comment by gl101** [comment]
Regarding the left to right output:
Turns out this had nothing to do with zkshell
It is a Putty issue. One needs, in Putty, to check the box "Disabling bidirectional text display"
